### ISSUE TITLE
A couple of inconsistencies/unexpected behaviour

### ISSUE THREAD

**Issue by sergei-maertens** [byashimov/django-controlcenter#10]
First of all, this project looks very promising! I've been trying it out for a couple of hours now, with this result as code:

```python
from django.db.models import Count
from django.db.models.functions import TruncMonth
from django.utils.translation import ugettext_lazy as _

from controlcenter import Dashboard, widgets
from dateutil.relativedelta import relativedelta

from bijleshuis.accounts.models import User


class NewUsersMixin:
    model = User
    title = _('New signups')
    values_list = ('month', 'count')

    def get_queryset(self):
        base = User.objects.all()
        qs = base.annotate(month=TruncMonth('date_joined')).values('month').annotate(count=Count('id'))
        return qs.order_by('-month')


class NewUsersLineChart(NewUsersMixin, widgets.SingleLineChart):
    class Chartist:
        options = {
            'reverseData': True,
        }

    def series(self):
        series = super().series
        series[0].insert(0, 0)
        return series

    def labels(self):
        labels = super().labels
        next_dt = labels[0] + relativedelta(months=1)
        return [dt.strftime('%b %y') for dt in [next_dt] + labels]


class NewUsersBarChart(NewUsersMixin, widgets.SingleBarChart):
    class Chartist:
        options = {
            'reverseData': True,
        }

    def series(self):
        series = super().series
        series.insert(0, 0)
        return series

    def labels(self):
        labels = super().labels
        next_dt = labels[0] + relativedelta(months=1)
        return [dt.strftime('%b %y') for dt in [next_dt] + labels]


class MainDashboard(Dashboard):
    widgets = (
        NewUsersLineChart,
        NewUsersBarChart
    )

```

As you can see, both widgets are almost identical, with the difference being that one is a line chart and the other a bar chart. They display the exact same data.

1. In the `SingleBarChart`, calling `super().series` results in a one-dimensional list, while the `LineBarChart` returns a two-dimensional list. I suspect this is a Chartist.js thing, but it's inconsistent on the Python side of things - it's the same one-dimensional dataset after all

2. There's a lot of code duplication like this. Initially, I tried something like
    ```python
    class NewUsersListChart(NewUsersMixin, widgets.SingleLineChart):
        pass
    ```
   this was kind of unexpected, and leads to a lot of code duplication when making small variants of widgets.

**Comment by byashimov** [comment]
I'm glad you like it.
As far as I can see, you can move `labels` method and `Chartist` class to the mixin. Then you have `series` left, which is fine as long as you want to have to different widgets.
The point is: I'm not sure if widget should manipulate with it's data depending on it's type. That kinda breaks OOP thing. That also means you will have multiple classes for every single simple case.

**Comment by sergei-maertens** [comment]
hrm, the point usually in Python mixins is that you don't inherit from anything specific, but then again, Django model mixins also require you to inherit from `models.Model`. I'll try out your suggestions asap and see if further improvements can be made, if I find anything worthy for a PR, I'll open one.

**Comment by byashimov** [comment]
"Eating your own dog food" is the only way I do write the code. Unfortunately, on my new job we do not use controlcenter. The only thing I can do is update code and tests for new versions of django.
So, any improvement is appreciated.
