### ISSUE TITLE
Usage outside of django admin

### ISSUE THREAD

**Issue by lggwettmann** [byashimov/django-controlcenter#13]
Hey guys,

would it make sense to use this package as user dashboard outside of the django admin? It looks great :)

**Comment by byashimov** [comment]
Oh, gosh. 
That's a great experience to come back in a while and take a look at the code I've written less than a year ago! What a mess! 

It MUST be able to work as a simple view but it doesn't. I'm gonna fix that up.

**Comment by byashimov** [comment]
Try [this branch](https://github.com/byashimov/django-controlcenter/blob/feature/set-optional-dashboard-view/controlcenter/views.py)

Create your own class based view with custom template and pass to a custom controlcenter instance. Then plugin it's urls.
