### ISSUE TITLE
how to add  short_description

### ISSUE THREAD

**Issue by Neilchen0111** [byashimov/django-controlcenter#16]
I add the short_description
but it doesn't work 

    def get_time(self, obj):
        return obj.time
    get_time.allow_tags = True
    get_time.short_description = 'Time'

    
    def get_user_count(self, obj):
        return obj.user_count
    get_user_count.allow_tags = True
    get_user_count.short_description = 'count'

**Comment by byashimov** [comment]
Do you use a custom template?
