### ISSUE TITLE
Release a new version

### ISSUE THREAD

**Issue by pauloxnet** [byashimov/django-controlcenter#19]
The last commits you merged from my pull request #15 permit controlcenter to works with Django 2.0.

Please bump a new version of controlcenter with this commits and release it on pypi.

Thank you

**Comment by byashimov** [comment]
Hi.
My tests fail with even 1.11. 
Fixed 1.11 but have to update for 2.x https://github.com/byashimov/django-controlcenter/tree/add-django-2-to-the-tests
I'll do that asap.

**Comment by pauloxnet** [comment]
Thanks

**Comment by byashimov** [comment]
Done. Please, let me know if something is wrong with the latest version.

**Comment by pauloxnet** [comment]
Thanks for the release. I'm going to test this last version.
