### ISSUE TITLE
update dashboard without refreshing

### ISSUE THREAD

**Issue by y0ngh00n** [byashimov/django-controlcenter#21]
Hi, I'm thankfully using this package for my django project as a dashboard.
I use some widgets in my dashboard page such as itemlist, piechart, linechart.
BTW, I have a question for you. 
As I mentioned in title, can i update my dashboard page without clicking f5 button?
I've founded that using Ajax or setTimeout function do it.
Please tell me if there is any way to do it.

**Comment by y0ngh00n** [comment]
Thanks very much for your advice.
I extended the dashboard template and override setInterval function javascript. 
It worked well about page reloading.
However, there are a few other issues occured.
As I said before, I used some charts including itemlist, piechart, timelinechart.
The problem is the querysets of pie-chart and timeline-chart are not update when page reloading unlike itemlist's. 
I uploaded my codes and github links here, please let me know if you have any ideas.

[git_link](https://github.com/fuzzysound/absusu/blob/reload_dashboard/absusu/dashboards.py)
` '''
Show AB test Dashboard
'''
from controlcenter import Dashboard, widgets
from controlcenter.widgets.core import WidgetMeta
from appserver_rest.models import UserAction
from experimenter.models import Experiment
from reward import KPI
from django.utils import timezone

# Active Experiments list
# eg) EXPERIMENTS = ['exp1', 'exp2', 'exp3', ]
EXPERIMENTS = [experiment.name for experiment in Experiment.objects.all()]

# to show a list of CTR for each experiment
class CTRList(widgets.ItemList):
    '''
    This widget displays a list of CTRs
    '''
    title = 'Click-through Rate'
    model = Experiment
    # multiple tables inner join queryset
    queryset = model.objects.filter(group__name__isnull=False).filter(goal__act_subject__isnull=False)\
        .values_list('name','group__name','goal__act_subject')
    list_display = ('name','group__name', 'goal__act_subject', 'get_ctr')

    def get_ctr(self, queryset):
        kpi = KPI()
        today = timezone.now().date()
        return kpi.CTR(*queryset, today)

# to show a pie chart how users are allocated for each group in experiment
class GroupPieChart(widgets.PieChart):
    '''
    This widget displays allocation of groups each experiment
    '''
    title = 'User Group Allocation'
    model = UserAction
    queryset = model.objects.order_by('ip').values('ip', 'groups').distinct()\
        .values_list('groups', flat=True)
    queryset2 = Experiment.objects.values_list('name', 'group__name')
    query_list = []
    # eg)[('exp1', 'control', 2)]

    for i in range(len(queryset2)):
        val_list = list(queryset2[i])
        val_count = eval("len(queryset.filter(groups__" + queryset2[i][0] + "=\'" + queryset2[i][1] + "\'))")
        val_list.append(val_count)
        query_list.append(tuple(val_list))

    class Chartist:
        options = {
            # Displays only integer values on y-axis
            'onlyInteger': True,

            # Visual tuning
            'chartPadding': 50,
            'labelDirection':'explode',
            'labelOffset':50,

            # donut chart
            'donut':True,
            'donutWidth': 50,
            'donutSolid': True,
        }

    def series(self):
        # Y-axis
        return [z for x, y, z in self.query_list]

    def labels(self):
        # Displays series
        return [x+' '+y+' ('+str(z)+')' for x, y, z in self.query_list]

    def legend(self):
        # Displays labels in legend
        return [x+' '+y for x, y, z in self.query_list]


class TimeLineChart(widgets.LineChart):
    # Display flow of CTRs during experiment
    title = 'Click-through Rate Time Series'
    leg_queryset = Experiment.objects.filter(group__name__isnull=False).values_list('name', 'group__name')
    val_queryset = Experiment.objects.filter(group__name__isnull=False).filter(goal__act_subject__isnull=False) \
                .values_list('name', 'group__name', 'goal__act_subject')

    class Chartist:
        # visual tuning
        options = {
            'axisX': {
                'labelOffset': {
                    'x': -50,
                    'y': 10
                },

            },
            'lineSmooth':False,
            'chartPadding': {
                'top': 50,
                'left': 50,
                'right': 50,
                'bottom': 20,
            }
        }

    # to specify experiment period
    @classmethod
    def elapsed_time(cls, exp_name):
        started = [datetime['start_time'] for datetime in Experiment.objects.filter(name=exp_name).values('start_time')][0]
        today = timezone.now()
        elapsed_time = (today - started).days + 3
        return elapsed_time

    # to specify experiment name, group name
    def legend(self):
        return [exp_name + ' ' + group_name for exp_name, group_name in self.leg_queryset]
    '''
    legend queryset format
    <ExperimentQuerySet [('exp1', 'A'), ('exp1', 'B'), ('exp2', 'control'), ('exp2', 'test')]>
    '''

    # to represent values on x-axis such as date. ex) 2018-01-18
    def labels(self):
        today = timezone.now().date()
        labels = [(today - timezone.timedelta(days=x)).strftime('%Y-%m-%d') for x in range(self.elapsed_time)]
        return labels
    '''
    labels format
    ['2018-01-18',
     '2018-01-17',
     '2018-01-16',
     '2018-01-15',
     '2018-01-14',
     '2018-01-13',
     '2018-01-12']
    '''

    # to represent values on y-axis which is calculated by values()
    def series(self):
        series = []
        for legend_idx in range(len(self.legend)-1, -1, -1):
            alist = []
            for label in self.labels:
                result = self.values.get(label, {})[legend_idx]
                alist.append(result)
            series.append(alist)
        return series
    '''
    series format
    [[0.6, 0.6, 0.5, 0, 0, 0, 0],
     [0.9, 0.778, 0.857, 0, 0, 0, 0],
     [0.538, 0.571, 0.5, 0, 0, 0, 0],
     [0.444, 0.429, 0.333, 0, 0, 0, 0]]
    '''

    # to calculate values such as CTR. ex) 0.725
    def values(self):
        kpi = KPI()
        values = dict()
        for label in self.labels:
            alist = list()
            for exp_name, group_name, act_subject in self.val_queryset:
                alist.append(kpi.CTR(exp_name, group_name, act_subject, label))
            values[label] = alist
        return values
    '''
    values format
    {'2018-01-12': [0, 0, 0, 0],
     '2018-01-13': [0, 0, 0, 0],
     '2018-01-14': [0, 0, 0, 0],
     '2018-01-15': [0, 0, 0, 0],
     '2018-01-16': [0.333, 0.5, 0.857, 0.5],
     '2018-01-17': [0.429, 0.571, 0.778, 0.6],
     '2018-01-18': [0.444, 0.538, 0.9, 0.6]}
        }
    '''

# Metaclass arguments are: class name, base, properties.
CTRLists = [WidgetMeta('{}CTRLists'.format(name),
                       (CTRList,),
                       {'queryset': (CTRList.queryset.filter(name=name)),
                        'title': name + ' CTR',
                        'changelist_url': (
                            Experiment, {'Experiment__name__exact': name})}) for name in EXPERIMENTS]

GroupPieCharts = [WidgetMeta('{}GroupPieCharts'.format(name),
                       (GroupPieChart,),
                       {'query_list': ([t for t in GroupPieChart.query_list if t[0].startswith(name)]),
                        'title': name + ' User Group',
                        'changelist_url': (
                            Experiment, {'Experiment__name__exact': name})}) for name in EXPERIMENTS]

TimeLineCharts = [WidgetMeta('{}TimeLineCharts'.format(name),
                       (TimeLineChart,),
                       {'leg_queryset': (TimeLineChart.leg_queryset.filter(name=name)),
                        'val_queryset': (TimeLineChart.val_queryset.filter(name=name)),
                        'elapsed_time': (TimeLineChart.elapsed_time(name)),
                        'title': name + ' CTR TimeSeries',
                        'changelist_url': (
                            Experiment, {'Experiment__name__exact': name})}) for name in EXPERIMENTS]

# Specifying which widgets to use
class AbsusuDashboard(Dashboard):
    widgets = (
        widgets.Group(CTRLists, width=widgets.LARGE),
        widgets.Group(GroupPieCharts, width=widgets.LARGE),
        widgets.Group(TimeLineCharts, width=widgets.FULL),
) `

**Comment by byashimov** [comment]
[Here](https://github.com/fuzzysound/absusu/blob/reload_dashboard/absusu/dashboards.py#L39). `values_list` fires immediately so you have _defined values directly in class_. Put it in a method or you lazy queryset methods, like `filter`, `exclude`, etc.

**Comment by y0ngh00n** [comment]
Sorry, I think I misspoke the problem.
What I want to ask that is when page reloaded, the pie-chart and timeline-chart aren't renewing the values based on the database that has changed. 
Now that I think about this question, it isn't exactly about controlcenter, but Django queryset. 
Still, do you have any other advice?

![image](https://user-images.githubusercontent.com/22536663/35575053-c7024d1c-061e-11e8-9273-4757b572cda2.png)

**Comment by byashimov** [comment]
Hey! Have you solved it? May I close the issue?

**Comment by y0ngh00n** [comment]
Yes! I've solved it using lazy evaluated queryset and defining values method for queryset manipulation. 
Your advice were really helpful, thank you!
