### ISSUE TITLE
Dashboards urls

### ISSUE THREAD

**Issue by editorgit** [byashimov/django-controlcenter#22]
I have in settings:

```
CONTROLCENTER_DASHBOARDS = (
    ('Leads', 'dashboards.Base'),
    ('Backlinks', 'apps.backlinks.dashboards.Backlinks'),
    ('Spiders', 'apps.spiders.dashboards.Spiders'),
)
```

But I get html without links:
```
<nav class="controlcenter__nav">
    <a class="controlcenter__nav__item" href="">Leads</a>
    <a class="controlcenter__nav__item" href="">Backlinks</a>
    <a class="controlcenter__nav__item" href="">Spiders</a>
</nav>
```

What I am doing wrong?
Python 3.6
Django 1.11
django-controlcenter==0.2.5

**Comment by byashimov** [comment]
Hi,
It's a bug. I'm fixing it right now.

**Comment by byashimov** [comment]
Could you try this branch? https://github.com/byashimov/django-controlcenter/tree/fix-navigation-menu

**Comment by editorgit** [comment]
Спасибо!
Теперь отлично работает.

2018-03-30 19:04 GMT+03:00 Murad Byashimov <notifications@github.com>:

**Comment by byashimov** [comment]
Ok. I will merge it asap.
