### ISSUE TITLE
bundling some chartist plugins

### ISSUE THREAD

**Issue by minusf** [byashimov/django-controlcenter#34]
would you consider bundling some basic chartist plugins?

the 2 basic ones (that come "out of the box" with jchart) i had in mind are `tooltips` and `legend`.

i am not sure why legends is a plugin, any graph with multiple datasets on it is useless without it...

https://github.com/CodeYellowBV/chartist-plugin-legend
http://gionkunz.github.io/chartist-js/plugins.html#tooltip-plugin

**Comment by minusf** [comment]
oh i see that you actually bundle `chartist-plugin-pointlabels`...

**Comment by byashimov** [comment]
Hello there!
If you really want to come it with controlcenter, please make a PR %)
There is a workaround to plug your stuff though https://django-controlcenter.readthedocs.io/en/latest/dashboards.html#media-class
