### ISSUE TITLE
Document/support how to use widgets on Django Admin Tools dashboard

### ISSUE THREAD

**Issue by andybak** [byashimov/django-controlcenter#4]
I've already got a dashboard and don't want another one. However - lovely declarative chart widgets would work very nicely as Django Admin Tools panels.

**Comment by byashimov** [comment]
I guess you might want to put this ticket on admin-tools tracker.
Also try this one: https://github.com/areski/django-admin-tools-stats

**Comment by andybak** [comment]
I suppose what I'm really asking is "Can you easily use widgets without using your dashboards?"

**Comment by byashimov** [comment]
I'm afraid that's not what I would ever do, so I didn't really covered that case. Admin-tools and Controlcenter are really different things. For instance, I use them both: the first one is an "advanced" menu, so I expect it to response quickly, with no delays. And the other one is for heavy statistics stuff, I know it can take some time.
Just imagine: every time you need to get somewhere from admin main page, you have to _wait_.

**Comment by andybak** [comment]
Fair point but could be solved by loading panel contents asynchronously.

I'll have a dig around and work out how to use widgets without using your dashboard as I think it could be useful in a range of scenarios.

If I do - would you be interested in adding it to the docs?

**Comment by byashimov** [comment]
Currently I'm working on another open-source project, but after that I'm going to continue with controlcenter. Ajax widgets are the next big thing I'm planning to release.

> If I do - would you be interested in adding it to the docs?

Sure. Any help would be appreciated.
