### ISSUE TITLE
Support for python 3.10

### ISSUE THREAD

**Issue by elenageo** [byashimov/django-controlcenter#65]
Using with python 3.10 the following error occurs

  File "/Users/elenag/.virtualenvs/consialinkenv/lib/python3.10/site-packages/controlcenter/widgets/core.py", line 88, in <module>
    class Group(collections.Sequence):
AttributeError: module 'collections' has no attribute 'Sequence'

This class has been move to collections.abc

**Comment by byashimov** [comment]
Do you use the latest version?

**Comment by elenageo** [comment]
Yes it is the latest version - the issue is with python 3.10, with python 3.9 it works

**Comment by byashimov** [comment]
> Yes it is the latest version - the issue is with python 3.10, with python 3.9 it works

Thank you for your report. Turns out the latest version hadn't been uploaded to pypi. Please upgrade to 0.3.1 https://pypi.org/project/django-controlcenter/

**Comment by elenageo** [comment]
Great. Thanks for the quick respone
