### ISSUE TITLE
Automatically redirect the main app url to the first dashboard.

### ISSUE THREAD

**Issue by fabiocaccamo** [byashimov/django-controlcenter#68]
In the admin, going to: `/admin/dashboard/` results in a 404 error, instead it would be much more useful/usable to redirect the user to the first dashboard, eg. 

`https://my-domain.com/admin/dashboard/` -> `https://my-domain.com/admin/dashboard/accounts/`

This would also simplify the url to remember/link for accessing the dashboard.

**Comment by byashimov** [comment]
Hey!
Unfortunately I don't have time for this project anymore. Could you provide with a PR please?
