### ISSUE TITLE
Summary line in ItemList

### ISSUE THREAD

**Issue by greeve** [byashimov/django-controlcenter#9]
I have a need to add a summary line to an item list widget. Currently I add one more item to the list of data that is a sum of the integer columns. The problem with this is the row is sorted with all the other data rows. What I would like is to have a summary row that allows me to define how a column is summarized and would be always placed at the bottom of the table (i.e. table footer). 

How would you accomplish this? I am willing to implement a solution but I want to do it in the way that makes the most sense.

**Comment by byashimov** [comment]
Seems like very specific case.
The easiest way to solve that is:

- add footer block to copy-pasted itemlist template
- extend your widget with a special method to return summary line values
- iter over it in your template

```python
class MyList(ItemList):
    @cached_property
    def values(self):
        ...
    def summary_values(self):
        yield from summary_raw_function(self.values):
```

ItemList is really depend on what return `values()`, I'm not sure there is an easy way to suggest a generic solution (to add it in controlcenter source code).
